- name: Start Busybox Image
  hosts: all
  tasks:
  - name: Busybox
    shell: |
      docker build -t "alpine:latest" .
      docker run -d alpine /bin/sh
#    docker_container:
#      name: mydata
#      image: busybox
#      state: started
