- name: Start Busybox Image
  hosts: all
  tasks:
  - name: Busybox
    shell: |
      docker-compose -f compose/docker-compose.yml build
#    docker_container:
#      name: mydata
#      image: busybox
#      state: started
