- name: Start Busybox Image
  hosts: all
  tasks:
  - name: Busybox
    shell: |
#      docker pull alpine
      docker build -t "alpine:latest" .
#    docker_container:
#      name: mydata
#      image: busybox
#      state: started
